### ISSUE TITLE
we could not able to save as vector pdf on server side.

### ISSUE THREAD

**Issue by sajumani** [zenozeng/p5.js-pdf#22]
Hi,

we were looking for save canvas on server side as vector pdf, here we not get exact solution.

May i know, is there is a possibility to save as vector pdf on server side...???

**Comment by zenozeng** [comment]
I am not sure, but maybe you can try svgcanvas and wkhtmltopdf?

**Comment by sajumani** [comment]
Thanks for your replay...

we got solution with https://github.com/zenozeng/p5.js-svg/

But We changed your p5-svg.js file

   p5.prototype.saveSVG = function() {
        // don't use slice on arguments because it prevents optimizations
        var args = arguments;
        args = [args[0], args[1], args[2]];

        var svg;

        if (args[0] instanceof p5.Graphics) {
            svg = args[0]._graphics.svg;
            args.shift();
        }

        if (typeof args[0] == "object") {
            svg = args[0];
            args.shift();
        }

        var filename = args[0];
        var ext = args[1];

        var p = this;
        this._makeSVGFrame({
            svg: svg,
            filename: filename,
            extension: ext,
            callback: function(err, frame) {
				
 $.ajax({
  type: "POST",
  url: "script.php",
  data: { 
     imgBase64: frame.imageData
  }
});
 $.ajax({
  type: "POST",
  url: "script.php",
  data: { 
     imgBase64: frame.imageData  // Passing dataurl to ajax page
  }
});
                //p.downloadFile(frame.imageData, frame.filename, frame.ext); // We hide default download
            }
        });
    };


// Server Side Script

$img = $_POST['imgBase64'];
$image_name = time().'_'.'P5.svg';
$file   = file($img);
$result = file_put_contents($image_name, $file);

**Comment by zenozeng** [comment]
:+1:

**Comment by zenozeng** [comment]
BTW, you can directly override p5Instance.downloadFile on the server side, then you can call saveSVG() directly.
